sensor_kit_base_link:
  # Main LiDAR at kit origin (Autoware How-to style)
  hesai_lidar:
    x: 0.000000
    y: 0.000000
    z: 0.000000
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000

  # NovAtel IMU body frame relative to kit
  imu_link:
    x: 0.943000
    y: -1.052432
    z: -1.319787
    roll: 0.447642
    pitch: -0.156325
    yaw: 3.120733

  # GNSS antenna ARP relative to kit (from your tape measurements)
  gnss_link:
    x: 1.317650
    y: -1.530262
    z: -0.487220
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000

