sensor_kit_base_link:
  # Main LiDAR at kit origin (Autoware How-to style)
  hesai_lidar:
    x: 0.000000
    y: 0.000000
    z: 0.054000
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000

  # NovAtel IMU body frame relative to kit
  imu_link:
    x: -0.0254
    y: 1.052432
    z: -1.319787
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.0

  # GNSS antenna ARP relative to kit (from your tape measurements)
  gps:
    x: -0.5588
    y: 0.5842
    z: -0.513337
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000
    
  # Camera front Wide relative to kit (camera mounting point)
  camera_front:
    x: -0.09270337361353152
    y: -0.2921
    z: -0.35409296057048567
    roll: 0.0
    pitch: 0.0
    yaw: -1.5708

