sensor_kit_base_link:
  # Main LiDAR at the kit origin (because the kit origin is defined at the LiDAR base)
  hesai_lidar:
    x: 0.000000
    y: 0.000000
    z: 0.000000
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000

  # NovAtel IMU relative to the LiDAR base (derived from your IMU and LiDAR base_link transforms)
  imu_link:
    x: 0.943000
    y: -1.052432
    z: -1.319787
    roll: 0.447642
    pitch: -0.156325
    yaw: 3.120733

  # GNSS: keep colocated with IMU for now (update later with antenna ARP offsets once measured)
  gnss_link:
    x: 0.000000
    y: 0.000000
    z: 0.000000
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000

