sensor_kit_base_link:
  # Main LiDAR at kit origin (Autoware How-to style)
  hesai_lidar:
    x: 0.000000
    y: 0.000000
    z: 0.054000
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000

  # NovAtel IMU body frame relative to kit
  imu_link:
    x: -0.0254
    y: 1.052432
    z: -1.319787
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.0

  # GNSS antenna ARP relative to kit (from your tape measurements)
  gps:
    x: -0.5588
    y: 0.5842
    z: -0.513337
    roll: 0.000000
    pitch: 0.000000
    yaw: 0.000000
    
  # Camera front Wide relative to kit (camera mounting point)
  camera_front:
    x: -0.01740005881108176
    y: -0.2921
    z: -0.40651892452708754
    roll: 0.0
    pitch: 0.0
    yaw: -1.5708
    
  camera_front_driver:
    x: 0.01740005881108176
    y: -0.2921
    z: -0.01740005881108176
    roll: 0.0
    pitch: 0.0
    yaw: -1.5708
  
  velodyne_left:
    x: 0.53
    y: 0.00
    z: -0.315
    roll: 0.063
    pitch: 0.714
    yaw: 0.090
    
  velodyne_right:
    x: -0.540
    y: 0.00
    z: -0.315
    roll: -0.009
    pitch: 0.773
    yaw: 3.136

