/**:
  ros__parameters:
    sensing:
      type: diagnostic_aggregator/AnalyzerGroup
      path: sensing
      analyzers:

        lidar:
          type: diagnostic_aggregator/AnalyzerGroup
          path: lidar
          analyzers:
            hesai:
              type: diagnostic_aggregator/AnalyzerGroup
              path: hesai
              analyzers:
                health_monitoring:
                  type: diagnostic_aggregator/AnalyzerGroup
                  path: health_monitoring
                  analyzers:

                    connection:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: connection
                      # Match typical Hesai/Nebula names you’ll see in /diagnostics
                      contains: [": hesai_connection", ": nebula_connection", ": lidar_connection"]
                      timeout: 3.0

                    temperature:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: temperature
                      contains: [": hesai_temperature", ": lidar_temperature", ": nebula_temperature"]
                      timeout: 3.0

                    rpm:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: rpm
                      contains: [": hesai_rpm", ": lidar_rpm", ": motor_rpm"]
                      timeout: 3.0

                    packet_drop:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: packet_drop
                      contains: [": lidar_packet_drop", ": udp_loss", ": packet_loss"]
                      timeout: 3.0

                    time_sync:
                      type: diagnostic_aggregator/GenericAnalyzer
                      path: time_sync
                      contains: [": ptp_sync", ": pps_status", ": time_sync"]
                      timeout: 3.0

        gnss:
          type: diagnostic_aggregator/AnalyzerGroup
          path: gnss
          analyzers:
            novatel_oem7:
              type: diagnostic_aggregator/AnalyzerGroup
              path: novatel_oem7
              analyzers:

                connection:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: connection
                  contains: [": gnss_connection", ": novatel_connection", ": oem7_connection"]
                  timeout: 3.0

                data:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: data
                  contains: [": gnss_data", ": novatel_data", ": oem7_data"]
                  timeout: 3.0

                antenna:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: antenna
                  contains: [": gnss_antenna", ": novatel_antenna", ": oem7_antenna"]
                  timeout: 3.0

                tx_usage:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: tx_usage
                  contains: [": gnss_tx_usage", ": novatel_tx_usage", ": oem7_tx_usage"]
                  timeout: 3.0

                spoofing:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: spoofing
                  contains: [": gnss_spoofing", ": novatel_spoofing", ": oem7_spoofing"]
                  timeout: 3.0

                jamming:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: jamming
                  contains: [": gnss_jamming", ": novatel_jamming", ": oem7_jamming"]
                  timeout: 3.0

                fix_topic_status:
                  type: diagnostic_aggregator/GenericAnalyzer
                  path: fix_topic_status
                  contains: [": fix topic status", ": gnss_fix_status", ": novatel_fix_status", ": oem7_fix_status"]
                  timeout: 3.0

