/**:
  ros__parameters:

    # Frames
    input_frame: base_link
    output_frame: base_link

    # Vehicle bounding box (MKZ body + mirrors + fenders)
    min_x: -1.2
    max_x: 4.05

    min_y: -1.10
    max_y: 1.10

    min_z: -0.15
    max_z: 2.3

    # Remove points INSIDE the box (vehicle self points)
    negative: true

    # Diagnostics (default Autoware value)
    processing_time_threshold_sec: 0.05
